# Generated by Django 4.2.8 on 2024-01-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_auto_20201129_1156"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="status",
            field=models.CharField(
                choices=[
                    ("teacher", "teacher"),
                    ("navttic-student", "navttic-student"),
                ],
                default="employee",
                max_length=20,
                null=True,
            ),
        ),
    ]
